<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Telebot</RootNamespace>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Bucketlab.Telebot</PackageId>
    <Version>0.0.75</Version>
    <Authors>TheHuginn</Authors>
    <Company>Bucketlab</Company>
    <Description>Библиотека клиент для телеграм</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
